### ISSUE TITLE
'MIDI' not declared in this scope

### ISSUE THREAD

**Issue by ghost** [316k/midi-ribbon-controller#2]
Hi,
first of all thank you for making this code. I am using it in order to learn how this stuff works, because I suck at coding so this one is fairly understandable. But there is a problem with MIDI, not exactly sure what is it about so I paste an error below. Thanks for any tips and help

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:13:0: warning: "MIDI_PITCHBEND_MIN" redefined

 #define     MIDI_PITCHBEND_MIN  -8192.0

 

In file included from C:\Program Files (x86)\Arduino\libraries\arduino_midi_library-5.0.2\src/MIDI.h:30:0,

                 from C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:1:

C:\Program Files (x86)\Arduino\libraries\arduino_midi_library-5.0.2\src/midi_Defs.h:46:0: note: this is the location of the previous definition

 #define MIDI_PITCHBEND_MIN      -8192

 

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:14:0: warning: "MIDI_PITCHBEND_MAX" redefined

 #define     MIDI_PITCHBEND_MAX  8191.0

 

In file included from C:\Program Files (x86)\Arduino\libraries\arduino_midi_library-5.0.2\src/MIDI.h:30:0,

                 from C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:1:

C:\Program Files (x86)\Arduino\libraries\arduino_midi_library-5.0.2\src/midi_Defs.h:47:0: note: this is the location of the previous definition

 #define MIDI_PITCHBEND_MAX      8191

 

C:\Users\RVW\Desktop\midi-ribbon-controller\midi.ino:7:0: warning: "MIDI_PITCHBEND_MIN" redefined

 #define  MIDI_PITCHBEND_MIN   -8192

 

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:13:0: note: this is the location of the previous definition

 #define     MIDI_PITCHBEND_MIN  -8192.0

 

C:\Users\RVW\Desktop\midi-ribbon-controller\midi.ino:8:0: warning: "MIDI_PITCHBEND_MAX" redefined

 #define  MIDI_PITCHBEND_MAX   8191

 

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:14:0: note: this is the location of the previous definition

 #define     MIDI_PITCHBEND_MAX  8191.0

 

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino: In function 'void do_stuff_because_midi_lib_is_broken()':

midi-ribbon-controller:54:5: error: 'MIDI' was not declared in this scope

     MIDI.sendControlChange(0, 0, 1);

     ^~~~

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:54:5: note: suggested alternative: 'MISO'

     MIDI.sendControlChange(0, 0, 1);

     ^~~~

     MISO

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino: In function 'void setup()':

midi-ribbon-controller:91:5: error: 'MIDI' was not declared in this scope

     MIDI.begin();

     ^~~~

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:91:5: note: suggested alternative: 'MISO'

     MIDI.begin();

     ^~~~

     MISO

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino: In function 'void loop()':

midi-ribbon-controller:134:9: error: 'MIDI' was not declared in this scope

         MIDI.sendPitchBend((double) pitch/127.0, MIDI_CHANNEL);

         ^~~~

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:134:9: note: suggested alternative: 'MISO'

         MIDI.sendPitchBend((double) pitch/127.0, MIDI_CHANNEL);

         ^~~~

         MISO

midi-ribbon-controller:145:9: error: 'MIDI' was not declared in this scope

         MIDI.sendNoteOn(note, velocity, MIDI_CHANNEL);

         ^~~~

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:145:9: note: suggested alternative: 'MISO'

         MIDI.sendNoteOn(note, velocity, MIDI_CHANNEL);

         ^~~~

         MISO

midi-ribbon-controller:157:9: error: 'MIDI' was not declared in this scope

         MIDI.sendPolyPressure(last_midi_note, velocity, MIDI_CHANNEL);

         ^~~~

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:157:9: note: suggested alternative: 'MISO'

         MIDI.sendPolyPressure(last_midi_note, velocity, MIDI_CHANNEL);

         ^~~~

         MISO

midi-ribbon-controller:164:9: error: 'MIDI' was not declared in this scope

         MIDI.sendNoteOff(last_midi_note, 0, MIDI_CHANNEL);

         ^~~~

C:\Users\RVW\Desktop\midi-ribbon-controller\midi-ribbon-controller.ino:164:9: note: suggested alternative: 'MISO'

         MIDI.sendNoteOff(last_midi_note, 0, MIDI_CHANNEL);

         ^~~~

         MISO

exit status 1

'MIDI' was not declared in this scope

**Comment by 316k** [comment]
Hi! Thanks for the interest in this (modest) project!

This code has not been touched in a while... (See #1)

First it seems like `MIDI_PITCHBEND_MIN` and `MIDI_PITCHBEND_MAX` might be already defined in the new MIDI arduino library, so the compiler doesn't like to see it redefined. You could try removing those definitions to remove some warnings, but that's not the core problem.

The biggest problem is that `MIDI` is not defined. From what it looks in the latest version of the arduino MIDI library ([here](https://github.com/FortySevenEffects/arduino_midi_library/tree/dev)), the code should start with a call to :

```c
// Create and bind the MIDI interface to the default hardware Serial port
MIDI_CREATE_DEFAULT_INSTANCE();
```
outside any function, directly after the include/define.

That's as far as I can help, my MIDI ribbon is archived somewhere in my boxes and I haven't touched arduino development for a while... Good luck!

**Comment by ghost** [comment]
I know, I know it's an old project. Thanks for reply. I really aprrieciate. I'll make some attempts tommorow.

**Comment by ghost** [comment]
Yeah, pasting this line of code solved all the problems. Thanks. Now the code is working.
